import './globals.css';
import type { Metadata } from 'next';
import NextUIApp from '@/providers/next';
import DashboardLayout from '@/layout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased dark`}>
        <NextUIApp>
          <DashboardLayout>{children}</DashboardLayout>
        </NextUIApp>
      </body>
    </html>
  );
}
